language: node_js
node_js:
- 8
script:
- npm run build
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: AKIAJEHNWJU3KLP7CEQQ
  secret_access_key: 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
  bucket: illinoisexpo.org
  local-dir: build
  acl: public_read_write
  on:
    repo: illinoisexpo/expo-website
  region: us-east-2
  skip_cleanup: true
