language: node_js
node_js:
- 8
script:
- npm run build
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: AKIAIRTDC3E2WPZ3YACA
  secret_access_key:
    secure: 6jyXA5G/UHoC97ilVM4FoUlIuBYdz1WXJm2S6K9BRyNe4uvmbDbl9zaAVHUcAwIvVy34y8lpDRzZe6v5SxlT+K77Xv/dE6s7Q6+R5n66DMS8w4ZOeAFSPtJVqtk/nSlEINTKztMnzJG9teZbzpGcjZn3MEJTVmAJVIciu2nOI2uSyq7Z8rQ5+5dWCd3jbkV9YuRfIKmsfzCxH0bdHB4bJ3j2a6o4dDIJYa7muDzdWjg4a5xxzxAh3lOOhvIR495WRjigZpfbkpePoBW0oZBEV+J/5Vpv+jx1TN2zBrpbjpCzDA0Ra/4ekTapTSNRI/RleSQCNXqYj3ingm94GAmFrlZguXSZOintSMAB03corkDDAHzuZdZdO0HpjtP1VFHDkUUy+AEy3Be8gFGcW86Je8NHCzoS+HR9HiJzsD0Gmh1WOKhb1AwoI3L7QOCQAG12d1e4MKvU82fo6WCGTzUQghlQPSn6BB3sRo+ZVaUDG6vFarYwFX9HY5EDFd2bbBJrU0UlEvpN/9I5WrOeQyp79FpzPDGxi5VB7RnlG5psH8MzJq1mkMLnjE8Y75LH2CTIomKVSaIA6rJ4IgsI4OYJ+7BzmVsA8J4yodZMSTeFA/7dus4p5ilqAH3i7k0FbdpPvxhpTc0Vh2pqy4j+kL5Ea9ZSkUri7PQ4EvI1oEKa+x4=
  bucket: illinoisexpo.org
  local-dir: build
  acl: public_read
  on:
    repo: illinoisexpo/expo-website
  skip_cleanup: true
  region: us-east-2
