language: node_js
node_js:
- 8
script:
- npm run build
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: AKIAJGIKNGN5PSMKECEA
  secret_access_key:
    secure: o7HVtCK84Icsrjs2d8jqJH1uoNE7AvpP/7IJwbWzZdE4BCgLznsrv0TZwKt8AqGpsV8iF2TQyMTSSxQJAvJk0eItRbVRBdKnNyjcZB68HDbl6ByWVh8EDWxwX6gfn6r7gTpWVw8LWGvlUQ3DtTCLnFeXHTfBgDV15f5RxTmwtDm77gDPCA+8hLsT1vCHZ2LrgvEEm6Bb2PwHvROy7AwsqS+QidM/gCbFAaFXTLcxK2ikGULjhu3qCHNGqLPdDjvEqFv0UOyO9GCgrsJqb8i5w88hypk6juuRZTuB9Fj/4VueBMds/Pq4Bmv/7B1g4xbL2a4mQUHH1YKmnHfWKWod3ALQawoDlO0wh1NSSYF3RVOC20g8z1jhtx0KmmLH9nonY34fPrrTWDi+z8ezixyz5T53TtL0qAa2FJYim3lf8iTvv7wxOW83rI2iTQCRrQxd5P7d0prUGtJQL2dkgAHKjeV3ffZfQMhUQ7gDSBPUafE7l/e2LbLcfRKwctoyp4BCMbPHWZY8getC1isK9KgEE8uL10pl4RJQLBdhZywL6iTCo8/O4zugHx4oDy3mWjU1CXlqBXNpiwl/dT6SgNtYqWlR4uDIWU1kUuJTGBV9Eg8H5JOE2NHvuofq41+wWktt1eaL5/hX2HLUSeXs+GcVEKysag5M64r4ovY6EXn9+3A=
  bucket: illinoisexpo.org
  local-dir: build
  acl: public_read
  on:
    repo: illinoisexpo/expo-website
  skip_cleanup: true
  region: us-east-2
