language: node_js
node_js:
- 8
script:
- npm run build
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: AKIAJR4PMAEZ77JFJBPQ
  secret_access_key:
    secure: 7MBX44m74gJFbFK4NNtCp3Ab2gwwUixUImixDh1DQeWeuaGbhVpoiymd95Ttpmii2WwDrAqORvXomKdjCfNPNPnXjPnLeKXF0VhADU2oz37dQGEpcFuanHRRCSzaj06SDqRqyB1A5Kit1Q7GbsCbeKwozX0YIQgIFcJLmNyacQv/dfT1IzwNRa13UL/WgEhsP+64LnFn1s8Ttio4Aj1jqn4ym/Lr9d9d3hi0gFFGyaCr2+s4tFCmW/hDJJ0N4DsvnIRxo6GX0aW3Y8a28nwWkhif+caIZjQS0b8VYJdc7ySnXAT2N1780y2PkGlk1Dle3h35hNdpUwR9IgKov8aWX7jWmDz2m6+tqdb7y0k0D6QU2RhNlYzramHT28/WI8uxX35MoTcVgsrX/IZR4f0gVrUi3v9dCk/rFCwDMtFTXY+YjWC9albu4ff266fshrY0sJcxgwxgs6ykv4KA6NNLllQZobkM9mnDd+KArxbA6rKRiflqGo5C+07vNeMUKrIc5W0YBWhwKlIjRkT0+26ZOZs/5DOFYePnPYUO0h5hRqDRcBet9LL/JE6S/1h4Gbjc2T06f8rg6oyQhnedHRxE82Du7e1Y9wMRbnN1FlOUOmm4MMYymYd62+Q/B99yvyHGCmhim1mS9FTShbia7XyOxuG1ZTndXCg+KMqvMOLDJhk=
  bucket: illinoisexpo.org
  local-dir: build/
  acl: public_read
  on:
    repo: illinoisexpo/expo-website
  region: us-east-2
  skip_cleanup: true
