language: node_js

node_js:
  - 8

script:
  - npm run build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules

deploy:
  provider: s3
  access_key_id: "AKIAJGIKNGN5PSMKECEA"
  secret_access_key: "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"
  bucket: "illinoisexpo.org"
  skip_cleanup: true
  region: "us-east-2"