language: node_js
node_js:
- 8
script:
- npm run build
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: AKIAJR4PMAEZ77JFJBPQ
  secret_access_key:
    secure: 3+UbCRIx1SvSVbDy1GPl268R6BEWLdMlgZ8P4zEWr81L+gvvvj4qkl4NTHFp3lTQy59JW79yWQtwr1mSsUAroFcaUwsFoSySbxhgu18is/IzYQ+A9Jps9aEvZYgaQTxocfWQQNiZp/LcrSIWkgeWLGWfCamenicH9E8JKQepwaMbh8gEo2TD4S6cbcRAgViXfmWerauYZZ5QDbBe4yIPunCoj79lIQXvt8iEU/zHwJhBrcItMOQVQYp8AuQVC8fkqjnL0zP/TtQ5lSFOE5OxZ9mhT2cLx2BKd32vcET8auhd8c7YU5gftwroa5Xc5wOFJxNlSRRDe17XkuKZ9gotLNXG8bTLP/W2EiBeq7nyGEjbGfeB7/6zv4uwPwX8uezqdm6qMTvG8t3kpnPFLQU7ut+30DyPfM6/LdyrRp9Qq9cLWFPMuMs6gz0t4UvPB90S3JbR7xyYV+BBGvp7u0P3+7hZPs5rxMzUFUURj/l7us+9y8O+Fbf8EJxm9ZkJ9fsvjfX+A75JWr/sarAhyWIq1YIJqfPdO3IrKaO9hvL8zk5JYUP0LKeQUCqVBRbROpcDEBRM3+bk9pZe+MshjQwczBKCm0s2pjAXjhrhvaBguKNoAQSy89KqGcqU980gvpj6xYbC5XPzYawb7I9T90ZgfrLbPfk2+lwK1F9A7rHIh2k=
  bucket: illinoisexpo.org
  local-dir: build
  acl: public_read
  on:
    repo: illinoisexpo/expo-website
  skip_cleanup: true
  region: us-east-2
